const defaultBanner = "IDE config";

// generated by the following code:
//
// require('gradient-string')([
//   { color: '#42d392', pos: 0 },
//   { color: '#42d392', pos: 0.1 },
//   { color: '#647eff', pos: 1 }
// ])('IDE config'))
//
// Use the output directly here to keep the bundle small.
const gradientBanner = " x  ";

export { defaultBanner, gradientBanner };
